apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testapp-deployment
  labels:
    app: testapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: gcr.io/glue-test/test-container:1b4766678494c59898ec1edacdeb9b26c4bb1147
        ports:
        - containerPort: 80
apiVersion: v1
kind: Service
metadata:
  name: testapp
  labels:
    service: testapp
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    service: testapp
